# Generated by Django 4.0.1 on 2022-02-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_admin_remove_user_is_administrator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='I_am_a',
        ),
        migrations.AddField(
            model_name='user',
            name='Check_this_if_you_are_a_parking_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
