# Generated by Django 4.0.1 on 2022-02-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_i_am_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Check_this_if_you_are_a_parking_administrator',
            new_name='Please_check_this_if_you_are_a_parking_administrator',
        ),
    ]
