# Generated by Django 4.0.1 on 2022-02-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_name', models.CharField(max_length=255)),
                ('full_address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Parking Lot',
                'verbose_name_plural': 'Parking Lots',
            },
        ),
    ]
