# Generated by Django 4.0.1 on 2022-04-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
