# Generated by Django 4.0.1 on 2022-04-11 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_parkinghistory_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
