# Generated by Django 4.0.1 on 2022-02-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='State',
            new_name='state',
        ),
    ]
