# Generated by Django 4.0.1 on 2022-04-10 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0002_initial'),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='in_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='out_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='parking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrators.parkinglot'),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='in_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='out_time',
            field=models.DateTimeField(null=True),
        ),
    ]
