# Generated by Django 4.0.1 on 2022-02-18 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_state_car_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='licence_plate_number',
            new_name='license_plate_number',
        ),
    ]
