# Generated by Django 4.0.1 on 2022-04-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_parkinghistory_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='payment_date',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
