# Generated by Django 4.0.1 on 2022-04-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_car_in_time_alter_car_out_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
