# Generated by Django 4.0.1 on 2022-04-02 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_parkinghistory_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinghistory',
            name='payment_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
