# Generated by Django 4.0.1 on 2022-02-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_licence_plate_number_car_license_plate_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='mark',
            new_name='make',
        ),
    ]
