# Generated by Django 4.0.1 on 2022-04-11 23:54

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_parkinghistory_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=localflavor.us.models.USStateField(max_length=2),
        ),
    ]
