# Generated by Django 4.0.1 on 2022-04-12 15:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_car_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuePaymentReminderScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking', models.CharField(max_length=255)),
                ('amount_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('has_been_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'due-payment-reminder',
                'verbose_name_plural': 'due-payment-reminders',
            },
        ),
    ]
