# Generated by Django 4.0.1 on 2022-04-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_duepaymentreminderscheduler'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DuePaymentReminderScheduler',
            new_name='DuePaymentReminder',
        ),
    ]
