# Generated by Django 4.0.1 on 2022-04-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_rename_duepaymentreminderscheduler_duepaymentreminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duepaymentreminder',
            old_name='amount_fee',
            new_name='amount_due',
        ),
    ]
