# Generated by Django 4.0.1 on 2022-04-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_rename_amount_fee_duepaymentreminder_amount_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duepaymentreminder',
            name='email',
        ),
        migrations.AddField(
            model_name='duepaymentreminder',
            name='email_to',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
