# Generated by Django 3.2.13 on 2022-04-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_remove_duepaymentreminder_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars'),
        ),
    ]
