# Generated by Django 4.0.1 on 2022-04-04 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='customer',
            field=models.ManyToManyField(blank=True, related_name='customers_who_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
