# Generated by Django 4.0.1 on 2022-02-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='capacities',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
