# Generated by Django 3.2.13 on 2022-04-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parking-lots'),
        ),
    ]
