# Generated by Django 4.0.1 on 2022-02-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0003_parkinglot_delete_administrator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'verbose_name': 'Parking Lot', 'verbose_name_plural': 'Parking Lots'},
        ),
    ]
